### ISSUE TITLE
The stickers dont save

### ISSUE THREAD

**Issue by vTpHuLk** [z1ntex/CSGO_WeaponStickers#19]
Idk if its only for me but after changing the map they just dont save and i have to put them again.

**Comment by crashzk** [comment]
## Installation
- Edit **`csgo/addons/sourcemod/configs/core.cfg`** => and set **`"FollowCSGOServerGuidelines"`** to **`"no"`**;
- Copy the folder structure to your gameserver;
- Setup **`database.cfg`**;
  - ***Example SQLite***:
```
    "csgo_weaponstickers"
    {
        "driver"        "sqlite"
        "database"      "csgo_weaponstickers"
    }
```
  - ***Example MySQL***:
```
    "csgo_weaponstickers"
    {
        "driver"        "mysql"
        "host"          "localhost"
        "database"      "mydb"
        "user"          "root"
        "pass"          ""
        //"timeout"     "0"
        "port"          "3306"
    }
```

**Comment by netohd** [comment]
Even with the correct configuration, apparently the plugin is actually resetting, but only when sqlite is used, in mysql it is normal.

**Comment by crashzk** [comment]
Test to see if it solves the problem. Remember to compile the source file and test this PR version.

https://github.com/z1ntex/CSGO_WeaponStickers/pull/23

**Comment by madeinred** [comment]
do i have to have both sqlite and mysql?

**Comment by crashzk** [comment]
> do i have to have both sqlite and mysql?

No, just one of the two.

The BUG in question happens in SQLIte, it doesn't save the players' choices, so whenever the map changes, it resets the stickers.

Fix for this bug is in PR: https://github.com/z1ntex/CSGO_WeaponStickers/pull/23

For you to test it, if you are using SQLite just compile the plugin and send it to your server. If you are using MySQL disregard.

**Comment by z1ntex** [comment]
Fixed
